export default [
  {
    fullName: "Francisco",
    middleName: "Martín",
    lastName: "Villarejo",
    nickName: "Fran",
    birthDate: "1993-08-07",
  },
  {
    fullName: "Damián",
    middleName: null,
    lastName: "Fixel",
    nickName: "Dami",
    birthDate: "1992-09-02",
  },
  {
    fullName: "Nicolás",
    middleName: null,
    lastName: "Grapsas",
    nickName: "El Poli",
    birthDate: "1994-04-15",
  },
  {
    fullName: "Lucas",
    middleName: "Alejandro",
    lastName: "Grula",
    nickName: "Panda",
    birthDate: "1989-02-07",
  },
  {
    fullName: "Johana",
    middleName: null,
    lastName: "Anez",
    nickName: "Joha",
    birthDate: "1991-01-16",
  },
  {
    fullName: "Alejandro",
    middleName: null,
    lastName: "Kler",
    nickName: "Ale K",
    birthDate: "1998-02-12",
  },
  {
    fullName: "Alejandro",
    middleName: null,
    lastName: "Mácula",
    nickName: "Ale M",
    birthDate: "1993-07-16",
  },
  {
    fullName: "Maximiliano",
    middleName: null,
    lastName: "Roitman",
    nickName: "Maxi",
    birthDate: "1982-05-14",
  },
  {
    fullName: "Leonardo",
    middleName: null,
    lastName: "Anglat",
    nickName: "Leo",
    birthDate: "2019-07-16",
  },
  {
    fullName: "Nicolás",
    middleName: null,
    lastName: "Cuellar",
    nickName: "Nico",
    birthDate: "2019-07-16",
    phrases: [
      "Borre los test porque no me compilaba",
      "Tu código es mi código",
      "Imaginate que mi brazo es como una librería...",
      "Bastante.. que hago test",
      "Estaba sola en medio del boliche 🎻",
      "No, lo que pasa es que me cancelaron el tren",
      "Llegue tarde porque tenía que lavar la ropa.",
      "Llegué tarde porque los gatos de mierda se estuvieron peleando toda la noche y no me dejaron dormir",
      "Estoy abierto a muchas cosas….",
      "Yo no la puse… , me la pusieron…",
      "Yo tambien quiero ser monje",
      "Hay que empezar a concientizarse de que no hay que subir cagadas a producción",
      "Me preocupa que todavía no hay olor a cerveza",
      "Vos no estás una noche y me tengo que ir con otro",
      "A mi me encanta la grasa",
      "En una tv el partido del mundial y en la otra porno",
      "La comimos entre todos",
      "Lo tenías abierto?",
      "Nos gusta estar juntitos!, es invierno!!",
      "Estoy pensando en mi mundo interior que tengo en mi cabeza",
    ],
  },
]