export default [
  {
    fullName: "Francisco",
    middleName: "Martín",
    lastName: "Villarejo",
    nickName: "Fran",
    birthDate: "1993-08-07",
  },
  {
    fullName: "Damián",
    middleName: null,
    lastName: "Fixel",
    nickName: "Dami",
    birthDate: "1992-09-02",
  },
  {
    fullName: "Nicolás",
    middleName: null,
    lastName: "Grapsas",
    nickName: "El Poli",
    birthDate: "1994-04-15",
  },
  {
    fullName: "Lucas",
    middleName: "Alejandro",
    lastName: "Grula",
    nickName: "Panda",
    birthDate: "1989-02-07",
  },
  {
    fullName: "Johana",
    middleName: null,
    lastName: "Anez",
    nickName: "Joha",
    birthDate: "1991-01-16",
  },
  {
    fullName: "Alejandro",
    middleName: null,
    lastName: "Kler",
    nickName: "Ale K",
    birthDate: "1998-02-12",
  },
  {
    fullName: "Alejandro",
    middleName: null,
    lastName: "Mácula",
    nickName: "Ale M",
    birthDate: "1993-07-16",
  },
  {
    fullName: "Maximiliano",
    middleName: null,
    lastName: "Roitman",
    nickName: "Maxi",
    birthDate: "1982-05-14",
  },
  {
    fullName: "Leonardo",
    middleName: null,
    lastName: "Anglat",
    nickName: "Leo",
    birthDate: "2019-07-16",
  },
  {
    fullName: "Nicolás",
    middleName: null,
    lastName: "Cuellar",
    nickName: "Nico",
    birthDate: "2019-07-16",
  },
  {
    fullName: "Vanesa",
    middleName: "Gisele",
    lastName: "Stricker",
    nickName: "Vane",
    birthDate: "1990-06-07",
  },
]